// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Commodity.Core.Configurations;
using Commodity.Core.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace Commodity.Core;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CropDimension> CropDimensions { get; set; }

    public virtual DbSet<CropPrice> CropPrices { get; set; }

    public virtual DbSet<StateDimension> StateDimensions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.CropDimensionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CropPriceConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.StateDimensionConfiguration());

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
