// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Commodity.Core.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Commodity.Core
{
    public partial interface IAppDbContextProcedures
    {
        Task<List<usp_GetCropPriceBySateDateResult>> usp_GetCropPriceBySateDateAsync(int? Id, DateTime? Date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
