// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Commodity.Core.Entities;

public partial class CropPrice
{
    public int Id { get; set; }

    public string Retail { get; set; }

    public string Wholesale { get; set; }

    public DateTime? Date { get; set; }

    public int? CropDimensionId { get; set; }

    public int? StateDimensionId { get; set; }

    public virtual CropDimension CropDimension { get; set; }

    public virtual StateDimension StateDimension { get; set; }
}