// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Commodity.Core.Entities
{
    public partial class usp_GetCropPriceBySateDateResult
    {
        public string image { get; set; }
        public string crop_name { get; set; }
        public string State_Name { get; set; }
        public string Retail { get; set; }
        public string Average_Retail { get; set; }
        public string Maximum_Retail { get; set; }
        public string Minimum_Retail { get; set; }
        public string Modal_Retail { get; set; }
        public string Wholesale { get; set; }
        public string Average_Wholesale { get; set; }
        public string Maximum_Wholesale { get; set; }
        public string Minimum_Wholesale { get; set; }
        public string Modal_Wholesale { get; set; }
    }
}
