// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Commodity.Core;
using Commodity.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Commodity.Core.Configurations
{
    public partial class CropPriceConfiguration : IEntityTypeConfiguration<CropPrice>
    {
        public void Configure(EntityTypeBuilder<CropPrice> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__CropPric__3214EC07B9A7AD73");

            entity.Property(e => e.Retail).IsUnicode(false);
            entity.Property(e => e.Wholesale).IsUnicode(false);

            entity.HasOne(d => d.CropDimension).WithMany(p => p.CropPrices)
            .HasForeignKey(d => d.CropDimensionId)
            .HasConstraintName("FK__CropPrice__CropD__47DBAE45");

            entity.HasOne(d => d.StateDimension).WithMany(p => p.CropPrices)
            .HasForeignKey(d => d.StateDimensionId)
            .HasConstraintName("FK__CropPrice__State__48CFD27E");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CropPrice> entity);
    }
}
