// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Commodity.Core;
using Commodity.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Commodity.Core.Configurations
{
    public partial class StateDimensionConfiguration : IEntityTypeConfiguration<StateDimension>
    {
        public void Configure(EntityTypeBuilder<StateDimension> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_States");

            entity.Property(e => e.StateName).HasColumnName("state_name");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StateDimension> entity);
    }
}
